### ISSUE TITLE
Some question about Kubernetes and CPU limits post

### ISSUE THREAD

**Issue by life1347** [danishprakash/danishpraka.sh#17]
https://github.com/danishprakash/danishpraka.sh/blob/10b15f4ee50e109df46d77dc467ccab2c978d38b/pages/posts/kubernetes-and-cpu-limits.md?plain=1#L74-L79

From the context, it should look like 
```
 cpu_quota_us=10ms 
 cpu_period_us=50ms 
```

---
And the second question is because we have 10 threads, so does that mean the formula should be `10/10 = 1ms` instead of `10/5 = 2ms`?

https://github.com/danishprakash/danishpraka.sh/blob/10b15f4ee50e109df46d77dc467ccab2c978d38b/pages/posts/kubernetes-and-cpu-limits.md?plain=1#L91

**Comment by danishprakash** [comment]
Ah yes, thanks for catching those. You are right, I've made a typo in the above cases.
